wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698879909.771149
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      2:
      - 2
      - 3
      - 12
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
epochs:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 128
