wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/dcgan/models/hyperparameter.py
    python_version: 3.8.10
    cli_version: 0.15.12
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698754458.794807
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 19
      - 23
      4: 3.8.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 128
